GET http://localhost:8080/employee/add?firstname=Василий&middlename=Васильевич&lastname=Семенов&departmentId=0&salary=120000
###
GET http://localhost:8080/employee/add?firstname=Василий&middlename=Васильевич&lastname=Семенов&departmentId=0&salary=120000
###
GET http://localhost:8080/employee/add?firstname=Семен&middlename=Семенович&lastname=Горбунков&departmentId=0&salary=120000
###
GET http://localhost:8080/employee/find?firstname=Семен&middlename=Семенович&lastname=Горбунков
###
GET http://localhost:8080/employee/remove?firstname=Семен&middlename=Семенович&lastname=Горбунков
###
GET http://localhost:8080/employee/list
###
GET http://localhost:8080/departments/all


